#!/bin/sh
exec docker run --rm --tty --interactive --volume $PWD:/app bigtruedata/sbt scala -deprecation -feature "$0" "$@"
!#
/* case class Expr examples from start of chapter 15
 *
 * shows convienance of these classes but not pattern matching
 * which is the main point
 */

// factory methods autogenerated
// no need for new Var("x")
var v = Var("x")

// factory methods are really nice when nested
val op = BinOp("+", Number(1), v)

// All obects implicitly get a val prefix and are fields
println(v.name)
println(op.left)

// natural toString() implementation added
println(s"op toString() is: ${op}")

// natural equals implementation added
assert(op.right == Var("x"))

// copy method added
// to copy and object while changing attributes
// e.g., copy op but change the operator
val opMinus = op.copy(operator = "-")


